services:
  postgres:
    image: postgres
    container_name: mypostgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tests
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d tests -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    image: mybackend
    container_name: mybackend
    build: .
    ports:
      - "5001:5000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env.test

