name: Pipeline Automatizado

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CI-ContinuousIntegration:
    runs-on: ubuntu-latest

  steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Criar .env.test
        run: |
          mkdir -p back-end
          echo "PORT=5000" >> back-end/.env.test
          echo "POSTGRES_USER=postgres" >> back-end/.env.test
          echo "POSTGRES_PASSWORD=postgres" >> back-end/.env.test
          echo "POSTGRES_DB=mydatabase" >> back-end/.env.test
          echo "DATABASE_URL=postgresql://postgres:postgres@mypostgres:5432/mydatabase" >> back-end/.env.test
          echo "NODE_ENV=test" >> back-end/.env.test

      - name: Subir serviços
        run: docker compose -f docker-compose-test.yml up --build --abort-on-container-exit

      - name: Limpar containers
        run: docker compose -f docker-compose-test.yml down -v